"""DB・ORM型を公開しない論理Repository Protocol。"""

from typing import Protocol

from .event_journal import CaseEvent
from .models import (
    Action,
    ActionHypothesis,
    AgentIteration,
    AgentRun,
    Artifact,
    Case,
    Checkpoint,
    Decision,
    DecisionReference,
    Hypothesis,
    Observation,
    ObservationArtifact,
    WorkItem,
    WorkItemDependency,
)


class CaseRepository(Protocol):
    def get_case(self, case_id: str) -> Case: ...

    def get_work_item(self, work_item_id: str) -> WorkItem: ...

    def list_work_items(self, case_id: str) -> tuple[WorkItem, ...]: ...

    def list_dependencies(self, case_id: str) -> tuple[WorkItemDependency, ...]: ...

    def get_hypothesis(self, hypothesis_id: str) -> Hypothesis: ...

    def list_hypotheses(self, case_id: str) -> tuple[Hypothesis, ...]: ...

    def list_decisions(self, case_id: str) -> tuple[Decision, ...]: ...

    def list_decision_references(
        self, case_id: str
    ) -> tuple[DecisionReference, ...]: ...

    def add_work_item(self, item: WorkItem) -> None: ...

    def update_work_item(self, item: WorkItem) -> None: ...

    def add_dependency(self, dependency: WorkItemDependency) -> None: ...

    def add_hypothesis(self, hypothesis: Hypothesis) -> None: ...

    def update_hypothesis(self, hypothesis: Hypothesis) -> None: ...

    def add_decision(self, decision: Decision) -> None: ...

    def add_decision_reference(self, reference: DecisionReference) -> None: ...


class ActionRepository(Protocol):
    def get_action(self, action_id: str) -> Action: ...

    def list_actions(self, case_id: str) -> tuple[Action, ...]: ...

    def list_action_hypotheses(self, case_id: str) -> tuple[ActionHypothesis, ...]: ...

    def get_observation(self, observation_id: str) -> Observation: ...

    def list_observations(self, case_id: str) -> tuple[Observation, ...]: ...

    def add_action(self, action: Action) -> None: ...

    def update_action(self, action: Action) -> None: ...

    def add_action_hypothesis(self, relation: ActionHypothesis) -> None: ...

    def add_observation(self, observation: Observation) -> None: ...


class ArtifactRepository(Protocol):
    def get_artifact(self, artifact_id: str) -> Artifact: ...

    def list_artifacts(self, case_id: str) -> tuple[Artifact, ...]: ...

    def list_observation_artifacts(
        self, case_id: str
    ) -> tuple[ObservationArtifact, ...]: ...

    def add_artifact(self, artifact: Artifact) -> None: ...

    def add_observation_artifact(self, relation: ObservationArtifact) -> None: ...


class RunRepository(Protocol):
    def list_runs(self, case_id: str) -> tuple[AgentRun, ...]: ...

    def list_iterations(self, case_id: str) -> tuple[AgentIteration, ...]: ...

    def add_run(self, run: AgentRun) -> None: ...

    def add_iteration(self, iteration: AgentIteration) -> None: ...


class EventJournal(Protocol):
    def list_events(self, case_id: str) -> tuple[CaseEvent, ...]: ...


class CheckpointRepository(Protocol):
    def latest(self, case_id: str) -> Checkpoint | None: ...

    def list_checkpoints(self, case_id: str) -> tuple[Checkpoint, ...]: ...
